import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';

import { getPool, getDb, closeDatabase } from '../src/db.js';
import { roles } from '../src/models/index.js';
import { eq } from 'drizzle-orm';
import rbacService from '../src/services/rbacService.js';
import { UserService } from '../src/services/userService.js';

/**
 * Dynamic role acceptance on user create/update.
 *
 * The backend must accept ANY role that exists and is active in the `roles`
 * table (created from the Roles & permissions page) — no static enum. A role
 * that does not exist, or has been deactivated, must be rejected with a clear
 * Arabic message. Fixtures use the reserved `urd-test%` username prefix and a
 * `URD اختبار` role name so the before-hook can self-heal a shared dev DB.
 */

const userService = new UserService();
const ids = {};
let roleCode;

async function cleanup(pool) {
  const d = async (t, p) => { try { await pool.query(t, p); } catch { /* ignore */ } };
  await d("DELETE FROM users WHERE username LIKE 'urd-test%'");
  await d("DELETE FROM roles WHERE name_ar LIKE 'URD اختبار%' OR code LIKE 'urdrole%'");
  await d("DELETE FROM branches WHERE name LIKE 'URD-BR-%'");
}

before(async () => {
  const pool = await getPool();
  await cleanup(pool);

  const ts = Date.now();
  const br = await pool.query(
    `INSERT INTO branches (name, is_active) VALUES ($1, true) RETURNING id`,
    [`URD-BR-${ts}`]
  );
  ids.branchId = br.rows[0].id;

  // Create a brand-new dynamic role exactly as the Roles & permissions UI does.
  const created = await rbacService.createRole(
    { nameAr: `URD اختبار ${ts}`, scope: 'branch', permissionKeys: ['sales:read'] },
    null
  );
  roleCode = created.code; // machine code generated by the service
  ids.roleId = created.id;
});

after(async () => {
  const pool = await getPool();
  await cleanup(pool);
  await rbacService.reload().catch(() => {});
  await closeDatabase().catch(() => {});
});

test('the new dynamic role is resolvable + active via rbacService.getRoleByCode', async () => {
  const role = await rbacService.getRoleByCode(roleCode);
  assert.ok(role, 'role exists in the RBAC cache');
  assert.equal(role.isActive, true);
  assert.notEqual(role.code, undefined);
});

test('creating a user with a freshly-created dynamic role SUCCEEDS', async () => {
  const user = await userService.create(
    {
      username: `urd-test-ok-${Date.now()}`,
      password: 'secret123',
      fullName: 'URD User',
      role: roleCode,
      assignedBranchId: ids.branchId,
    },
    null
  );
  ids.userId = user.id;
  assert.equal(user.role, roleCode, 'user is bound to the dynamic role code');
});

test('the newly-created user APPEARS on page 1 of the list (newest-first)', async () => {
  // Regression: list() had no ORDER BY, so with pagination a freshly-created
  // user could land on a later page and seem to "disappear". It must now be on
  // top of page 1, regardless of how many users exist or its dynamic role.
  const res = await userService.list({ page: 1, limit: 10 }, { role: 'admin' });
  const found = res.data.find((u) => u.id === ids.userId);
  assert.ok(found, 'created user is present on page 1');
  assert.equal(found.role, roleCode, 'its dynamic role is returned, not filtered out');
  assert.equal(res.data[0].id, ids.userId, 'newest user is listed first');
});

test('the created user is NOT excluded when filtering by its dynamic role', async () => {
  const res = await userService.list({ page: 1, limit: 10, role: roleCode }, { role: 'admin' });
  assert.ok(res.data.some((u) => u.id === ids.userId), 'role filter returns the user');
  assert.ok(res.data.every((u) => u.role === roleCode), 'only that role is returned');
});

test('updating a user to the same dynamic role SUCCEEDS', async () => {
  const updated = await userService.update(ids.userId, { role: roleCode }, null);
  assert.equal(updated.role, roleCode);
});

test('the created user can be removed', async () => {
  await userService.remove(ids.userId, null);
  const res = await userService.list({ page: 1, limit: 10, isActive: false }, { role: 'admin' });
  // remove() deactivates (soft delete); the user must still be findable as inactive.
  assert.ok(res.data.some((u) => u.id === ids.userId), 'removed user is now inactive');
});

test('creating a user with a NON-EXISTENT role FAILS with a clear Arabic message', async () => {
  await assert.rejects(
    () =>
      userService.create(
        {
          username: `urd-test-bad-${Date.now()}`,
          password: 'secret123',
          fullName: 'URD Bad',
          role: 'no_such_role_xyz',
          assignedBranchId: ids.branchId,
        },
        null
      ),
    /غير موجود أو غير فعّال/
  );
});

test('a DEACTIVATED role can no longer be assigned (create + update fail)', async () => {
  const db = await getDb();
  // Deactivate the role in the DB and refresh the RBAC cache.
  await db.update(roles).set({ isActive: false }).where(eq(roles.id, ids.roleId));
  await rbacService.reload();

  await assert.rejects(
    () =>
      userService.create(
        {
          username: `urd-test-deact-${Date.now()}`,
          password: 'secret123',
          fullName: 'URD Deact',
          role: roleCode,
          assignedBranchId: ids.branchId,
        },
        null
      ),
    /غير موجود أو غير فعّال/
  );

  // Re-assigning the existing user to the now-inactive role must also fail.
  await assert.rejects(
    () => userService.update(ids.userId, { role: roleCode }, null),
    /غير موجود أو غير فعّال/
  );
});
